# Generated by Django 4.1.7 on 2023-02-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=55, verbose_name='Тэг')),
                ('url', models.URLField(verbose_name='Ссылка на пост')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('outlink', models.URLField(verbose_name='Ссылки на сторонние сервисы')),
                ('content', models.TextField(verbose_name='Текст поста')),
            ],
        ),
    ]
